const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Business Analysis',
      items: [
        { type: 'autogenerated', dirName: 'business' },
        'template-business-plan',
      ],
    },
    {
      type: 'category',
      label: 'Develop',
      items: [
        {
          type: 'category',
          label: 'Architecture',
          items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },
        {
          type: 'category',
          label: 'Frontend',
          items: [{ type: 'autogenerated', dirName: 'frontend' }],
        },
        {
          type: 'category',
          label: 'Backend',
          items: [{ type: 'autogenerated', dirName: 'backend' }],
        },
        {
          type: 'category',
          label: 'Database',
          items: [{ type: 'autogenerated', dirName: 'database' }],
        },
        {
          type: 'category',
          label: 'API',
          items: [{ type: 'autogenerated', dirName: 'api' }],
        },
        {
          type: 'category',
          label: 'Technical',
          items: [{ type: 'autogenerated', dirName: 'technical' }],
        },
        'template-technical-spec',
        {
          type: 'category',
          label: 'Agents',
          items: [{ type: 'autogenerated', dirName: 'agents' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      items: [
        'workflow-intro',
        'agentos-ticket-system-guidelines',
        {
          type: 'category',
          label: 'Tickets',
          items: [{ type: 'autogenerated', dirName: 'tickets' }],
        }
      ],
    },
  ],
};

export default sidebars;
